# Generated by Django 6.1.1 on 2026-09-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='categoria',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('prato_principal', 'Prato Principal'), ('sobremesa', 'Sobremesa'), ('bebida', 'Bebida')], default='prato_principal', max_length=20),
        ),
    ]
